### ISSUE TITLE
GridCol is not exported

### ISSUE THREAD

**Issue by ganlhi** [heetch/flamingo#107]
As of version 1.9.3, the `GridCol` component is not exported from `flamingo/packages/react/src/components/index.js`.
Therefore an app cannot use the `Grid` component.

**Comment by ugogo** [comment]
Hi @ganlhi, sorry for the late response.
The `GridCol` component is exported alongside the `Grid` one.

You can use it as follow:
```
import { Grid } from '@heetch/flaming-react`

export default () => (
  <Grid>
    <Grid.Col>...</Grid.Col>
    <Grid.Col>...</Grid.Col>
    <Grid.Col>...</Grid.Col>
  </Grid>
)
```

Hope it helps!

**Comment by ganlhi** [comment]
Hi @ugogo !
Thank you for the answer. I didn't see that when I read the code, now I found it.
Sorry for the irrelevant issue.
