### ISSUE TITLE
RFC: components organization and naming

### ISSUE THREAD

**Issue by ugogo** [heetch/flamingo#137]
I'd like to propose an RFC about our components organization

### Current organization
```
components/
  Button/
    index.js
    index.stories.js
```

#### What's wrong here?
When you have multiple tabs open, it quickly become hard to know what file you are editing
<img width="1242" alt="Screenshot 2020-04-21 at 13 45 10" src="https://user-images.githubusercontent.com/5040476/79862449-63461a00-83d6-11ea-9ab4-97960010c6a3.png">

### Solution 1: root them all

```
components/
  Button.js
  Button.stories.js
```
Even though this solution looks nice now, it will quickly be complicated to navigate into the components folder and the total amount of components will grow overtime 

### Solution 2: :smart:
```
components/
  Button/
    index.js
    Button.js
    Button.stories.js
```

This solution is almost the same as the current organization we have, but the `index.js` file will only do one thing
```
export { default as Button } from './Button';
// we can also export components constants here
```

By doing this, we will always be editing the `{component}.js` file, which will improve the editor tabs readability.
It will also improve the navigation experience when searching for a component

<img width="620" alt="Screenshot 2020-04-21 at 13 49 46" src="https://user-images.githubusercontent.com/5040476/79862888-10b92d80-83d7-11ea-89b9-860464a02bb4.png">
vs

<img width="612" alt="Screenshot 2020-04-21 at 13 50 06" src="https://user-images.githubusercontent.com/5040476/79862890-1151c400-83d7-11ea-9746-72e86de2c4c7.png">

Cheers 👋

**Comment by obedparla** [comment]
Haha I love this. I was thinking the same thing, I don't like having `index.js` for everything.

I have another proposal:

```
components/
  Button/
    Button.js
    Button.stories.js
```

And then in `index.js`

`export {Button} from './Button/Button`. 

No need to have an `index.js` file :) 

We could also export everything explicitly, no `default`, but this isn't a big deal.

**Comment by ugogo** [comment]
I find it weirder to have twice the component's name into the path 😄 
```
import Button from 'components/Button/Button`
```

**Comment by obedparla** [comment]
I have no strong preference, I haven't used any `index` files for years, but having them isn't a big deal either. 

As long as we can name the component its proper name it's good

**Comment by keanan** [comment]
I personally much prefer named files over index - they are much easier to find/open in the IDE and you can see what you're working on. It's a small tradeoff to see double names in the import.

**Comment by ugogo** [comment]
Alright, so let's go for
```
components/
  Button/
    Button.js
    Button.stories.js
```

Will be done in the `v3` 👍

**Comment by keanan** [comment]
Solution 2 is perfect, since we can keep component files named, sorry if I was un-clear.
