### ISSUE TITLE
How to call heetch  from an external application

### ISSUE THREAD

**Issue by Sofiane23i** [heetch/flamingo#254]
Hello, 

i working on a project based openstreetmap, using user current position and maker position, i would like to call heetch drivers directly from my application. is there an api solution for that like it presents in google maps direction 
https://www.google.com/maps/dir/?api=1&origin=values,&destination=values

thanks.

**Comment by ganlhi** [comment]
Hello! 
I'm sorry but we don't expose a public API about drivers.
